### ISSUE TITLE
ErrorOccured

### ISSUE THREAD

**Issue by greyDoll** [NVlabs/PWC-Net#98]
Could you please show me any solutions to this problem？
`Executing /usr/bin/caffe test -model tmp/deploy.prototxt -weights ./model/pwc_net.caffemodel -iterations 2 -gpu 0
I1126 15:47:04.038105 22832 caffe.cpp:275] Use GPU with device ID 0
I1126 15:47:04.109428 22832 caffe.cpp:279] GPU device name: GeForce GTX 1060 3GB
E1126 15:47:04.137107 22832 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E1126 15:47:04.235828 22832 common.cpp:121] Cannot create Curand generator. Curand won't be available.
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 59:22: Message type "caffe.LayerParameter" has no field named "augmentation_param".
F1126 15:47:04.237218 22832 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: tmp/deploy.prototxt
*** Check failure stack trace: ***
    @     0x7f570520574d  google::LogMessage::Fail()
    @     0x7f5705207911  google::LogMessage::SendToLog()
    @     0x7f570520527d  google::LogMessage::Flush()
    @     0x7f57052082c9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f57058ebc01  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f57058855a7  caffe::Net<>::Net()
    @     0x55f066d48337  test()
    @     0x55f066d4637b  main
    @     0x7f5703f9cb97  __libc_start_main
    @     0x55f066d46d6a  _start
./tmp/frame_0010_forward.flo
./tmp/frame_0011_backward.flo
mv: cannot stat './tmp/pwc-net-pred-0000000.flo': No such file or directory
mv: cannot stat './tmp/pwc-net-pred-0000001.flo': No such file or directory`

I would appreciate it if you could answer it for me

**Comment by marinaoliveira** [comment]
I have a similar problem: 
```
Executing /home/marina/Desktop/PWC-NET/flownet2-master/build/tools/caffe.bin test -model tmp/deploy.prototxt -weights ./model/pwc_net.caffemodel -iterations 2 -gpu 0
I0525 15:20:19.297240 17445 caffe.cpp:237] Use GPU with device ID 0
I0525 15:20:19.302290 17445 caffe.cpp:241] GPU device name: 
F0525 15:20:19.302311 17445 common.cpp:160] Check failed: error == cudaSuccess (804 vs. 0)  forward compatibility was attempted on non supported HW
*** Check failure stack trace: ***
    @     0x7f4caf09e0cd  google::LogMessage::Fail()
    @     0x7f4caf09ff33  google::LogMessage::SendToLog()
    @     0x7f4caf09dc28  google::LogMessage::Flush()
    @     0x7f4caf0a0999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4caf730322  caffe::Caffe::SetDevice()
    @     0x559424f8c222  (unknown)
    @     0x559424f8a28a  (unknown)
    @     0x7f4cae2f7b97  __libc_start_main
    @     0x559424f8ab0a  (unknown)
./tmp/frame_0010_forward.flo
Traceback (most recent call last):
  File "./proc_images.py", line 126, in <module>
    evaluate_model(template, model_filename, image1_list, image2_list, out_flow_list, out_vis_list, scale_ratio)
  File "./proc_images.py", line 87, in evaluate_model
    uv  = flow_read(flow_fn)
  File "/home/marina/Desktop/PWC-NET/PWC-Net-master/Caffe/flow_io.py", line 31, in flow_read
    f = open(filename,'rb')
FileNotFoundError: [Errno 2] No such file or directory: './tmp/pwc-net-pred-0000000.flo'
```
Were you able to solve the problem?
